name: SonarQube Analysis

on:
  push:
    branches: [ main ]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN_BOOKING_RUANGAN: ${{ secrets.SONAR_TOKEN_BOOKING_RUANGAN }}
